on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest-large
    steps:
    - name: Install Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff  # v5
      with:
        go-version: 1.22.x
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      with:
         path: './src/github.com/segmentio/bump_version'
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4
      with:
        path: /home/runner/.cache
        key: ${{ runner.os }}-go-v4-${{ hashFiles('**/*.go') }}
        restore-keys: |
          ${{ runner.os }}-go-v4-
    # staticcheck needs this for GOPATH
    - run: |
        echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
        echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
    - name: Download dependencies
      run: go get -t -v ./...
      working-directory: './src/github.com/segmentio/bump_version'
    - name: Run tests
      run: make ci
      working-directory: './src/github.com/segmentio/bump_version'
