on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
    - uses: actions/checkout@v4
      with:
         path: './src/github.com/kevinburke/bump_version'
    - uses: actions/cache@v4
      with:
        path: /home/runner/.cache
        key: ${{ runner.os }}-go-v4-${{ hashFiles('**/*.go') }}
        restore-keys: |
          ${{ runner.os }}-go-v4-
    # staticcheck needs this for GOPATH
    - run: |
        echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
        echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
    - name: Download dependencies
      run: go get -t -v ./...
      working-directory: './src/github.com/kevinburke/bump_version'
    - name: Run tests
      run: make ci
      working-directory: './src/github.com/kevinburke/bump_version'
